<?php

class TFunc{
    public static function console($arg){
        echo "<script>console.log('" . $arg . "');</script>";
    }

    public static function artist_reservation_chk($row){
        if($row['is_sunday']==1){
            $regular_break_day[] = 0;
        }
        if($row['is_monday']==1) {
            $regular_break_day[] = 1;
        }
        if($row['is_tuesday']==1) {
            $regular_break_day[] = 2;
        }
        if($row['is_wednesday']==1) {
            $regular_break_day[] = 3;
        }
        if($row['is_thursday']==1) {
            $regular_break_day[] = 4;
        }
        if($row['is_friday']==1) {
            $regular_break_day[] = 5;
        }
        if($row['is_saturday']==1) {
            $regular_break_day[] = 6;
        }

        return $regular_break_day;
    }

    public static function strToFillZero($val, $zero){
        $tmp = sprintf('%0'.strval($zero).'d', (int)$val) ;
        return $tmp;
    }

    public static function checkPC(){
        $mobile_agent = "/(iPod|iPhone|Android|BlackBerry|SymbianOS|SCH-M\d+|Opera Mini|Windows CE|webOS|PalmOS)/";
        if(preg_match($mobile_agent, $_SERVER['HTTP_USER_AGENT'])){
            return "Mobile";
        }else{
            return "PC";
        }
    }
}

class TChFunc extends TFunc{
    public static function console($arg, $type=0)
    {
        if($type < 1) {
            echo $arg + '<br>';
        }else{
            parent::console($arg); // TODO: Change the autogenerated stub
        }
    }
}




